/**
 * MLR (Medical/Legal/Regulatory) approval model (brief §6.7, §17). Content and
 * compliance-sensitive rules require MLR sign-off before going active. Approvals
 * are versioned; content is never overwritten in place (PDF §6 versioning).
 */

import type { ApprovedAnswerId, MlrApprovalId, SafetyStatementId } from "@lib/ids";
import type { ApprovedAnswer, ContentService, SafetyStatement } from "@modules/content";

export type MlrState = "not_submitted" | "in_review" | "approved" | "rejected" | "expired";

export interface MLRApproval {
  id: MlrApprovalId;
  state: MlrState;
  version: number;
  approvedBy?: string;
  approvedAt?: string;
  expiresAt: string | null;
}

export function isMlrActive(a: MLRApproval, now: Date = new Date()): boolean {
  if (a.state !== "approved") return false;
  if (a.expiresAt && new Date(a.expiresAt).getTime() < now.getTime()) return false;
  return true;
}

/**
 * MLRService — the human review loop over ingested content. Parsed content lands
 * as `in_mlr` (never retrievable). A reviewer approves it → `active` (and it is
 * published to retrieval so the rep can cite it) or rejects it → `retired`.
 * Nothing generated by parsing can be spoken until it clears this gate.
 */
export class MlrService {
  constructor(
    private readonly content: ContentService,
    /** Called when an answer becomes active — the container wires this to index it. */
    private readonly onActivate?: (a: ApprovedAnswer) => Promise<void>,
  ) {}

  /** Content awaiting review (parsed/uploaded but not yet approved). */
  async listPending(): Promise<ApprovedAnswer[]> {
    return (await this.content.listAnswers()).filter((a) => a.mlr.status === "in_mlr");
  }

  async listPendingSafety(): Promise<SafetyStatement[]> {
    return (await this.content.listSafetyStatements()).filter((s) => s.mlr.status === "in_mlr");
  }

  async approve(id: ApprovedAnswerId): Promise<ApprovedAnswer | null> {
    const a = await this.content.setAnswerStatus(id, "active");
    if (a?.supersedes) {
      // A revision replaces its original ATOMICALLY on approval: the old version retires,
      // so exactly one version of the passage is ever retrievable/spoken.
      await this.content.setAnswerStatus(a.supersedes, "retired");
    }
    if (a && this.onActivate) await this.onActivate(a);
    return a;
  }

  async reject(id: ApprovedAnswerId): Promise<ApprovedAnswer | null> {
    return this.content.setAnswerStatus(id, "retired");
  }

  async approveSafety(id: SafetyStatementId): Promise<SafetyStatement | null> {
    const s = await this.content.setSafetyStatus(id, "active");
    if (s) await this.content.retireOtherActiveSafetyStatements(s.id);
    return s;
  }

  async rejectSafety(id: SafetyStatementId): Promise<SafetyStatement | null> {
    return this.content.setSafetyStatus(id, "retired");
  }
}
